### ISSUE TITLE
Get rid of local-exec provisioners as IBM Cloud Schematics don't support it

### ISSUE THREAD

**Issue by ashishth09** [IBMSpectrumComputing/spectrum-schematics-cluster#22]
https://github.com/IBMSpectrumComputing/spectrum-schematics-cluster/blob/master/main.tf#L45-L47

**Comment by lospringliu** [comment]
Thanks, let me try to move it to remote-exec for now.
Looks bare metal support is not mature yet, supporting user_metadata would be perfect

**Comment by ashishth09** [comment]
You mean https://github.com/IBM-Bluemix/terraform-provider-ibm/blob/master/ibm/resource_ibm_compute_bare_metal.go#L68 is not working for you?

**Comment by lospringliu** [comment]
yes, I can not get any user_metadata with command `curl https://api.service.softlayer.com/rest/v3/SoftLayer_Resource_Metadata/UserMetadata.txt`

**Comment by lospringliu** [comment]
for bare metal. vm instance works perfect

**Comment by lospringliu** [comment]
I built the provider using master branch and applied a bare metal, this time I got the user_metadata with https://api.service.softlayer.com/rest/v3/SoftLayer_Resource_Metadata/UserMetadata.txt

In this case, I do not need local-exec, nor file and remote-exec provisioners:)
